### ISSUE TITLE
Delete a namespace

### ISSUE THREAD

**Issue by fastsol** [adbario/slim-secure-session-middleware#10]
I am wondering if there is a way to delete a namespace?  I see the deleteFrom() but that seems to need a $key also, I want to simply provide a $namespace and have it delete that whole namespace in the session.  In this example I mean there would be a session like $_SESSION['validated_uploads'] = ['whatever', 'whatever'];  I want to delete the whole validated_uploads namespace.

The clearFrom() now works, thank you.

Maybe this is another instance of me overthinking things, or I'm just not understanding how it works.

**Comment by adbario** [comment]
I added a new method for this: deleteNamespace()
```php
$session->deleteNamespace('namespace_to_delete');
```

By the way, there are major changes coming to this script soon(ish), when I get extra time. Old methods will stay mostly intact, but add() and addTo() will change completely, future push() and pushTo() methods will have the same functionality later on.

**Comment by fastsol** [comment]
That's perfect.  Thank you!
