### ISSUE TITLE
Sessions not persisting across routes

### ISSUE THREAD

**Issue by avdwalt** [adbario/slim-secure-session-middleware#12]
Hi,

When a call is made to route /login it performs user authentication checks and stores the users data in a namespace session etc. 

If I then make a call to route /session at a later stage and try to retrieve the previously stored user data in the namespace session I keep getting NULL returned.

Note - currently running my website on localhost with PHP 7> 

Any assistance would be appreciated?

**Comment by SaphiLC** [comment]
same issue, is driving me crazy

**Comment by avdwalt** [comment]
I am ready to pull my hair out at this point!!! I know I must be doing something silly but I have now tried everything and nothing is working! 

Could it be localhost WampServer causing the issue?

**Comment by SaphiLC** [comment]
actually, just found the issue O_O
im very new with middleware but after i changed the order of my middleware, it started working, 
```
$app->add(new \Middleware\LastRequest($container));
$app->add(new \Adbar\SessionMiddleware($settings['session']));
```
looks like mine needs to go before adbar's O:

**Comment by avdwalt** [comment]
Aah awesome find! Yeah new myself with middleware.
How have you setup your routing? 

My issue seems to be specific with routes not able to pickup session variables

**Comment by SaphiLC** [comment]
i use controllers for my routes, not sure if thats what you are asking for n_nU

**Comment by adbario** [comment]
Slim middlewares are used in reverse order, which means that all classes that use session, has to be on code before the session.

**Comment by avdwalt** [comment]
mmmm, as in, would you be able to give me a example of how you implemented you sessions with your routing? to make sure I am doing it correctly

**Comment by adbario** [comment]
Personally I use app wide middlewares with this, not per routes. Feel free to share a sample of your code, but if you have two different middlewares, session and some other one that uses session, then session should be the last (which makes it first).

**Comment by zweeen** [comment]
Same as @avdwalt , I can't access to the previously stored user data in the namespace session.

It seems that Sessions are not persisting across routes dunno why.

Here is my index.php

```
<?php

	use \Psr\Http\Message\ServerRequestInterface as Request;
	use \Psr\Http\Message\ResponseInterface as Response;


	//Adding Slim 3 framework
	require __DIR__ . '/../vendor/autoload.php';

	//Configuration file
	require __DIR__ . '/settings/settings.php';

	$app = new \Slim\App($settings);

        //Routes
        require __DIR__ . '/routes/routes.php';

        //Controllers
        require __DIR__ . '/controllers/MainController.php';
        require __DIR__ . '/controllers/OrdersController.php';
        require __DIR__ . '/controllers/CreateAccountController.php';
        require __DIR__ . '/controllers/FileController.php';

	//Dependencies
        require __DIR__ . '/dependencies/session.php';
	require __DIR__ . '/dependencies/db.php';
	require __DIR__ . '/dependencies/generateCustomerPassword.php';
	require __DIR__ . '/dependencies/PHPMailer.php';

	$container = $app->getContainer();
	$app->add(new Mailer($container));

	//Middlewares
	require __DIR__ . '/middlewares/middlewares.php';
	//$app->add( new ExampleMiddleware($settings['session']));

	$app->run();
```

When using route **/login** I set the session  :

         `$this->container->session->set('userTest', 'test');`

and immedialty after I do :

         `$test = $this->container->session->get('userTest');`

the **`$test`** variable equals = **"test"**

But when changing route and using e.g **/getTest**

I do this : 

         `$test = $this->container->session->get('userTest');`

the **`$test`** variable equals = **"null"**

**Comment by adbario** [comment]
The OP had an issue with middlewares being in wrong order, as Slim runs them in reverse order. And what does that session.php contain in your dependencies?

**Comment by zweeen** [comment]
Hi @adbario,

In my session.php I got this :

```
<?php

    // Get container
    $container = $app->getContainer();

    // Inject a new instance of SESSION in the container
    $container['session'] = function ($container) {
        return new \Adbar\Session(
            $container->get('settings')['session']['session_1']['namespace']
        );
    };
```

Thanks for taking from your time to answer :)

**Comment by adbario** [comment]
How does your middlewares.php look like?

If that ExampleMiddleware is replaced by something real that uses sessions, it has to be called before session middleware, not after.

**Comment by zweeen** [comment]
My  **middlewares.php**  does nothing I just removed this line 

Btw it looks like :

```
<?php

use \Psr\Http\Message\ServerRequestInterface as Request;
use \Psr\Http\Message\ResponseInterface as Response;

class ExampleMiddleware
{
    /**
     * Example middleware invokable class
     *
     * @param  \Psr\Http\Message\ServerRequestInterface $request  PSR7 request
     * @param  \Psr\Http\Message\ResponseInterface      $response PSR7 response
     * @param  callable                                 $next     Next middleware
     *
     * @return \Psr\Http\Message\ResponseInterface
     */
    public function __invoke($request, $response, $next)
    {
        $response->getBody()->write('BEFORE');
        $response = $next($request, $response);
        $response->getBody()->write('AFTER');

        return $response;
    }
}
```

**Comment by adbario** [comment]
But what does your middlewares.php file look like?

**Comment by zweeen** [comment]
Sorry in my  middlewares.php  there is the code above.

**Comment by adbario** [comment]
So you're not calling the session middleware globally, you call it per route? Can you post an example of that?

**Comment by zweeen** [comment]
Of course : 

My route that is calling a controller :

`$app->post('/login',  \FileController::class . ':login');`

and inside my controller :

```
public function login($request, $response, $args) {
      $test = $this->container->session->get('userTest');
      $newResponse = $response->withJson($test);

      return $newResponse;
   }
```

sorry i just updated my code

**Comment by adbario** [comment]
I don't see you calling the session middleware anywhere at all, which means the session is not started properly: https://github.com/adbario/slim-secure-session-middleware#middleware

**Comment by zweeen** [comment]
Ok I understand what you said, I have just added this :

` $app->add(new \Adbar\SessionMiddleware($settings['settings']['session']));`

Still got the variable returned **null**

**Comment by adbario** [comment]
Can you show me the contents of ```$settings['settings']['session']['clientAppUser']``` which you use with the middleware and ```$settings['settings']['session']['session_1']['namespace']``` which you use with depency container?

**Comment by zweeen** [comment]
I am really sorry @adbario  I  wanted to change the variable name when I copy/pasted my code. It's why I get you confused.

I use only one array settings :

```
<?php

	$settings = [
	    'settings' => [

	    'displayErrorDetails' => true,
            'session' => [
                'clientAppUser' =>  [
                    // Session cookie settings
                    'name'           => 'slim_session',
                    'lifetime'       => 24,
                    'path'           => '/',
                    'domain'         => null,
                    'secure'         => false,
                    'httponly'       => true,

                    // Set session cookie path, domain and secure automatically
                    'cookie_autoset' => true,

                    // Path where session files are stored, PHP's default path will be used if set null
                    'save_path'      => null,

                    // Session cache limiter
                    'cache_limiter'  => 'nocache',

                    // Extend session lifetime after each user activity
                    'autorefresh'    => false,

                    // Encrypt session data if string is set
                    'encryption_key' => null,

                    // Session namespace
                    'namespace'      => 'clientAppUser'
                ]
            ]
	    ],
	];
```

**Comment by zweeen** [comment]
So when I call the session middleware I do :

`$app->add(new \Adbar\SessionMiddleware($settings['settings']['session']['clientAppUser']));`

And when I use my dependency container I do  :

```
<?php

    // Get container
    $container = $app->getContainer();

    // Inject a new instance of SESSION in the container
    $container['session'] = function ($container) {
        return new \Adbar\Session(
            $container->get('settings')['session']['clientAppUser']['namespace']
        );
    };

```

**Comment by adbario** [comment]
Yeah it's hard to pick up your code from these pieces...

Anyway, I just did a simple test by using the same settinngs as you have and it seems to work just fine. Route / is setting a name "John" to session and on route /name it gets picked up.

```php
<?php
use \Psr\Http\Message\ServerRequestInterface as Request;
use \Psr\Http\Message\ResponseInterface as Response;

// Settinngs
$settings = [
    'settings' => [

        'displayErrorDetails' => true,
        'session' => [
            'clientAppUser' =>  [
                // Session cookie settings
                'name'           => 'slim_session',
                'lifetime'       => 24,
                'path'           => '/',
                'domain'         => null,
                'secure'         => false,
                'httponly'       => true,

                // Set session cookie path, domain and secure automatically
                'cookie_autoset' => true,

                // Path where session files are stored, PHP's default path will be used if set null
                'save_path'      => null,

                // Session cache limiter
                'cache_limiter'  => 'nocache',

                // Extend session lifetime after each user activity
                'autorefresh'    => false,

                // Encrypt session data if string is set
                'encryption_key' => null,

                // Session namespace
                'namespace'      => 'clientAppUser'
            ]
        ]
    ],
];

// Composer autoload
require __DIR__ . '/../vendor/autoload.php';

// Slim
$app = new \Slim\App($settings);

// Get container
$container = $app->getContainer();

// Dependencies
$container['session'] = function ($container) {
    return new \Adbar\Session(
        $container->get('settings')['session']['clientAppUser']['namespace']
    );
};

// Middlewares
$app->add(new \Adbar\SessionMiddleware($settings['settings']['session']['clientAppUser']));

// Routes
$app->get('/', function (Request $request, Response $response) {
    $this->session->set('name', 'John');
    $response->getBody()->write("Setting a name (John) to session here.");
    return $response;
});

$app->get('/name', function (Request $request, Response $response) {
    $response->getBody()->write("The name is " . $this->session->get('name'));
    return $response;
});

// Run Slim
$app->run();
```

If you're declaring your routes before dependencies and middleware, you should try to move the routes to last, just before running the app. I'm not sure how Slim handles the order of these, but this might be one issue.

**Comment by zweeen** [comment]
Thank you a lot Adbario for your time and for the code above, really.
I tested your code and it works perfectly.

I problably have not write well my code. I will review it and will inform you why my code didn't work.
I wish you a happy merry Christmas :D

**Comment by adbario** [comment]
You're welcome :)

**Comment by zweeen** [comment]
Sorry to reopen this issue.

So I tested my api created from your code above in an angularJs application. I still have the same problem : I can set variable but I am unable to get this variable.

But when testing the two routes "/" and "/name" in another context, e.g I just open a Chrome tab an type the url "http://localhost/api/" or "http://localhost/api/name" everything is fine. I can set and get the variable.

So my question is why in my angularJs context calling "http://localhost/api/name" with ajax request the route return me **null** and with the 'normal' context the route return me the variable desired ?

**UPDATE**:
Sorry to came a bit late. I have found where my error came from. I had to 'Allow credentials' : 
`angular.module('myApp')

.config(['$httpProvider', function($httpProvider) {
  $httpProvider.defaults.withCredentials = true;
}])`

Thanks again @adbario for this great session middleware  you have made :)

**Comment by adbario** [comment]
Your sessions seem to work fine then, that issue has something to do with how you use AngularJS or might be a CORS issue as well. I don't use AngularJS myself and can't help you with this.

**Comment by JosemarOdia** [comment]
Hello!

I'm facing this problem too.
I followed the steps of the documentation to do the dependency injection and also in the middleware, however, in the login I record the user in the session, but when directing to another page the session no longer exists.

The order of inclusion of the files is as follows:

$ settings = require __DIR__. '/src/config/settings.php';
$ app = new \ Slim \ App ($ settings);

require __DIR__. '/dependencies.php';

require __DIR__. '/middleware.php';

require __DIR__. '/routes.php';

$ app-> run ();

And the logo at the beginning of middleware I put this snippet of code:

$ app-> add (new \ Adbar \ SessionMiddleware ($ container-> get ('settings') ['session']));

Another problem I noticed is that if I try to use $ this-> session-> set () on the routes, Slim complains that the method is null.

I'm using Slim 3.

**Comment by adbario** [comment]
Hi JosemarOdia, based on the information you sent, it's impossible to say what's wrong there. You need to drop at least paste your dependencies and middleware files here.

Also you should look at my example at https://github.com/adbario/slim-secure-session-middleware/issues/12#issuecomment-353797510 which works very well.

**Comment by JosemarOdia** [comment]
Hello, thank you for your response.

I used his example, and really, ran the session between the routes. However, I have now changed your example to my need, access the middleware session as follows, and it did not work. Look:

Can you help me?



```
<?php
use \Psr\Http\Message\ServerRequestInterface as Request;
use \Psr\Http\Message\ResponseInterface as Response;


// Composer autoload
require __DIR__ . '/../vendor/autoload.php';

// Settinngs
$settings = [
    'settings' => [
        'displayErrorDetails' => true, // set to false in production
        'addContentLengthHeader' => false, // Allow the web server to send the content-length header
        // Session
        'session' => [
            'name'           => 'slim_session',
            'lifetime'       => 24,
            'path'           => '/',
            'domain'         => null,
            'secure'         => false,
            'httponly'       => true,
            'cookie_autoset' => true,
            'save_path'      => null,
            'cache_limiter'  => 'nocache',
            'autorefresh'    => false,
            'encryption_key' => 'HelpDeskDS',
            'namespace'      => 'ds_app'
        ],
    ],
];

// Slim
$app = new \Slim\App($settings);

// Get container
$container = $app->getContainer();

// Dependencies
$container['session'] = function ($container) {
    return new \Adbar\Session(
        $container->get('settings')['session']['namespace']
    );
};

// Middlewares
$app->add(new \Adbar\SessionMiddleware($settings['settings']['session']));

$app->add(function (Request $request, Response $response, callable $next) {
    $response->getBody()->write("Middleware name is:" . $this->session->get('name'));
    return $response;
});

// Routes
$app->get('/', function (Request $request, Response $response) {
    $this->session->set('name', 'Jose');
    $response->getBody()->write("Setting a name (John) to session here.");
    return $response;
});

$app->get('/name', function (Request $request, Response $response) {
    $response->getBody()->write("The name is " . $this->session->get('name'));
    return $response;
});

// Run Slim
$app->run();
```

**Comment by adbario** [comment]
Your middlewares are in wrong order. Slim runs them on reverse order, so you need to call the session middleware after the ones that are using session. Now you're trying to use session before even starting a session, which will not work.

https://www.slimframework.com/docs/v3/concepts/middleware.html

**Comment by JosemarOdia** [comment]
Thank you very much for your patience and understanding.
Really, it was my lack of attention, I'm starting on Slim.

**Comment by SaphiLC** [comment]
sorry for opening this again, but i tested the code @JosemarOdia sent and even if you change the order of the middleware, is still giving nothing (i can only access session vars from my controllers...) i just opened a new issue in case you can help us with this, im just unable to use sessions inside middleware (i load session middleware last, just before getting the routes and nope, nothing)
