### ISSUE TITLE
Weirdest "bug"

### ISSUE THREAD

**Issue by SaphiLC** [adbario/slim-secure-session-middleware#13]
When i have opera's dev tools open, i get this error
```
Warning: session_start(): Failed to read session data: user (path: N;D:/UwAmp/bin/apache/sessions) in D:\UwAmp\www\slim\vendor\adbario\slim-secure-session-middleware\src\SessionMiddleware.php on line 157
```
and when i close the bar the page works, now if i delete the session while having the dev tools open and refresh the page, the page works, but as soon as i close dev tools and refresh, i get the same session_start bug @_@ no idea whats going on

**Comment by adbario** [comment]
This has definitely something to do with Opera then, sorry I have no help for this. Maybe try Chrome, there's pretty awesome dev tools.

**Comment by SaphiLC** [comment]
opera is chrome n_nU
no idea what could be going on?
these are my settings:
```
'session' => [
	'name' => 'appSession',
	'lifetime' => 60*24,
	'path' => '/',
	'domain' => null,
	'secure' => true,
	'httponly' => true,
	'cookie_autoset' => true,
	'save_path' => '../temp/sessions',
	'cache_limiter' => 'nocache',
	'autorefresh' => true,
	'encryption_key' => 'FheU&jy#gcyTHuqMyG!YnYjM3CqarP^pJ!Y7!9Pm6ez!k^^$t6%R5A&W$&kQ2$2uBP*e$gwPM&A4^TDJFE3AKNCz8KsZAQ%dQujp',
	'namespace' => null,
],
```

**Comment by adbario** [comment]
No idea really, if you're using https-connection as you have 'secure' => true and ir your save_path is correct. Also try other browser just to find out if this is something related to Opera. Opera shares the same engine with Chrome, but there definitely are some differencies on background as well.
