### ISSUE TITLE
PHP 7 Only?

### ISSUE THREAD

**Issue by richp10** [adbario/slim-secure-session-middleware#2]
I think this is written for PHP7 - for example it calls random_bytes which is not available in earlier versions. 

Took me ages to work this out!  Might be good to add to documentation if I am correct..

**Comment by adbario** [comment]
Thanks for posting! There's scalar type hinting that is not supported by PHP 5, fixing it soon.

**Comment by adbario** [comment]
PHP 5 support was just added.

**Comment by kingmad** [comment]
Correct me if I am wrong but `SecureSessionHandler` still uses `random_bytes` function (introduced in PHP7) what makes session encryption feature unusable for < PHP7.
I performed some tests with https://github.com/paragonie/random_compat which provides PHP 5.x polyfill for `random_bytes()` and `random_int()` and it looks like everything works properly so maybe it's worth to mention about it in documentation.

**Comment by adbario** [comment]
Hi! You're absolutely right with this, it's my mistake and will be fixed. I used the same Paragonies script before but somehow this was forgotten after moving to PHP7. Thanks for posting.

**Comment by adbario** [comment]
PHP5.x support is fixed.
