### ISSUE TITLE
Not working in IE 11

### ISSUE THREAD

**Issue by samvel33651** [adbario/slim-secure-session-middleware#5]
Hi,

slim-secure-session-middleware always return new sessionId each time we refresh page.

**Comment by adbario** [comment]
Hi, there should be no way to have a new session id on every page load, unless you destroy session or regenerate the id. If this only happens with IE 11, it's definitely a browser issue with cookies, as session itself is stored on server. If same thing happens with other browsers as well, can you show me your code how you implement sessions.

**Comment by samvel33651** [comment]
Hi , no it happens only in IE11.

**Comment by adbario** [comment]
This is definitely a browser issue then. Check if your cookies are enabled on your page etc.
