### ISSUE TITLE
Little fix for PHP 7.X

### ISSUE THREAD

**Issue by JCatnip** [adbario/slim-secure-session-middleware#6]
Hello man !

I just fixed a little bug in PHP 7.X (7.1 in my case) in the `read` function of `SecureSessionHandler` class,
you should replace `return ($data) ? $this->decrypt($data) : null;` by `return ($data) ? $this->decrypt($data) : '';` to avoid an annoying warning ;-)

Good work, very useful !

**Comment by adbario** [comment]
Hi, you're totally correct with this, it's fixed now. Thanks for posting!
