### ISSUE TITLE
Some problems

### ISSUE THREAD

**Issue by patrioticcow** [adbario/slim-secure-session-middleware#7]
Problem 1:

If I do: `$this->session->setTo('records', $request->getParams());`
then the session would look like

    'first_name' => 'john'
    'last_name' => 'doe'

and that is fine. But then I do: `$this->session->addTo('records', ['some_key' => 'some_value']);`
and the result is

    'first_name' => 'john'
    'last_name' => 'doe'
    'some_key' => [
        '0' => 'some_value'
    ]

Problem 2:

This doesn't work: `$this->session->getFrom('records')` if the `$key` is missing. I want to just do that and get back all data from that namespace

Maybe the `getFrom` mehtod should be changed to have this:  

    $result = $key ? $this->get($key, $default) : $_SESSION[$namespace];

**Comment by adbario** [comment]
Hi,

Problem 1: works as expected. Methods add() and addTo() adds values to arrays with numeric keys. If you want i.e. a list of users, you also need to use add() or addTo() for the initial value, not set() or setTo().

Problem 2: yes you're correct, there's no option currently to get all data from other namespace. I will add allFrom() method for this soon.

**Comment by patrioticcow** [comment]
Problem 1. Makes sense, just not super intuitive.

**Comment by adbario** [comment]
What would be an optimum way to handle adding values to an array for you? Numeric and unique keys are the only way to prevent accidentally overwriting data, and if you need to add someting, numeric key arrays are surely the best and native way to store the list.

**Comment by patrioticcow** [comment]
Yeah, except that I don't see the issue with overwriting the data. In most cases I came across, overwriting is what one wants. If you are keen on holding to the previous data, you could have a special key that u can access to get the history.

```
'first_name' => 'john'
'last_name' => 'doe'
```

after `first_name` change

```
'first_name' => 'new first name'
'last_name' => 'doe'
'_history' => [
   'first_name' => [
        '0' => 'john',
        '1' => 'older entry'
    ]
]
```
not sure what the use case would be for this, I guess it can be useful.

**Comment by patrioticcow** [comment]
If you care about a "solution" to this, you can reopen the ticket and get some community feedback, or I could submit some pull requests

**Comment by adbario** [comment]
Sorry for late reply. I don't see that "history" implementation as a part of this project, that would be needed for only very specific situations and for you I would suggest extending my class with your needs of forking your own. Current add() and addTo() methods are pretty useful now, as they implement the native way of adding values to an array with numeric keys:
```php
$array->add('names', 'John');
vs.
$array['names'][] = 'John';
```

**Comment by adbario** [comment]
Hey I'm back to working with these scripts now and had a thought about your issue number 1. If you first set the data to a session with
```$this->session->setTo('records', $request->getParams());```

and then if you need to add more data on same level as you described, could you use this?
```$this->session->setTo('records.some_key', 'some_value');```

This way 'records' would look like:
```php
'first_name' => 'john',
'last_name' => 'doe',
'some_key' => 'some_value'
```

One option would be to use Laravel-style add() method, which adds a key-value pair to an array the way you're looking for, if the key doesn't exist already. If the key exists, then the value will stay untouched. That way ```$this->session->addTo('records', ['some_key' => 'some_value']);``` would end up with the result you're looking for.

**Comment by patrioticcow** [comment]
What I'm thinking is that this approach with the dot notation is still not intuitive enough. 
Also would have to write some more code

``` php

// initial session record
function firstView($request)
{
    $this->session->setTo('records', $request->getParams());
}

function secondView($request)
{
    $params = $request->getParams();

    // this works if I know  the key and value I want
    $this->session->setTo('records.some_key', $params['some_key']);

    // or a loop to set them all
    foreach ($params as $key => $param) {
        $this->session->setTo('records.' . $key, $param);
    }
}

// my approach
function secondView($request)
{
    // this would be cleaner and save a few lines of code
    // this would have to behave the same like the foreach from above
    $this->session->setTo('records', $request->getParams());
}
```

**Comment by adbario** [comment]
Hey, method setTo() should work exactly the way you want to in your approach.
```php
// Post parameters
$_POST = [
    'first_name' => 'john',
    'last_name' => 'doe'
];

// Store parameters to the session namespace 'records'
$this->session->setTo('records', $request->getParams());

// Would be the same as
$_SESSION['records']['first_name'] = 'john';
$_SESSION['records']['last_name']  = 'doe';
```

Now when you do exactly the same thing again with different parameters, the new parameters wil be saved under the 'records' key and only overwriting the old items with same key as new items.

This actually works even if there's a specific key set in setTo() method:
```php
// Store parameters to the session namespace 'records'
// under key 'values'
$this->session->setTo('records', 'values', $request->getParams());

// Would be the same as
$_SESSION['records']['values']['first_name'] = 'john';
$_SESSION['records']['values']['last_name']  = 'doe';
```

**But this last behaviour will be changed in next updates to:**
```php
// Store parameters to the session namespace 'records'
// under key 'values'
$this->session->setTo('records', 'values', $request->getParams());

// Would be the same as
$_SESSION['records']['values'] = [
    'first_name' => 'john',
    'last_name'  => 'doe'
];
```

which means that if you give a specific key to set() or setTo() methods, the old values within that key will be removed while adding the new ones. This will be more like the native way of saving data to arrays and it alllowes using dots in key names as well, as dot notation would be applied only for the keys in method, not for the values.

______

So the solutions for you would be to use the setTo() method without specific key:
```php
// Overwrites previous items with the same key
$this->session->setTo('records', $request->getParams());
```

Also I will be changing the add() and addTo() methods so that they will use key-value pairs, but they only add new record if the same key doesn't exist already:
```php
// Adds only items that doesn't exist already
$this->session->addTo('records', $request->getParams());
```

And to make everything work with set() and setTo() methods with specific key, there could be a merge() and mergeTo() methods for this. This merge() method would save you from using separate namespace for your records as well:
```php
// Storing initial records, overwrites all previous items in 'records'
$this->session->set('records', $request->getParams());

// Storing records while keeping the old records, only overwrites records with the same key
$this->session->merge('records', $request->getParams());
```
