### ISSUE TITLE
How to append a value in a key

### ISSUE THREAD

**Issue by fastsol** [adbario/slim-secure-session-middleware#8]
Hello,
I really like your script and it works well.  I am currently reconstructing a project with new better techniques and code base so I decided to use your script.  The problem I am having is that I need a way to "append" a value to an already set key.  I have tried messing with the Dot file and copying the add() to create a append() and then modifying that to try and make it work.  So far I am lost as this seems t be over my head.

Here is an example:
``
array[
  'item' => 'something'
]
``
I want to be able to do by appending:
``
array[
  'item' => 'something something else'
]
``
Your help and guidance would be greatly appreciated!

**Comment by adbario** [comment]
Hey, in your example you're just overwriting a key-value pair. So, if the value is string and you want to change it (in your case add something to it), you need to read the original string and add your new string to it, then store it back to same key.

```php
// Set 'item' to 'something'
$session->set('item', 'something');

// Add a string to 'item' value 
$session->set('item', $session->get('item') . ' something else');

// Get 'item' current value, returns 'something something else'
echo $session->get('item');
```

Same thing can be done with native array style:
```php
// Set 'item' to 'something'
$session['item'] = 'something';

// Add a string to 'item' value 
$session['item'] .= ' something else';

// Get 'item' current value, returns 'something something else'
echo $session['item'];
```

**Comment by fastsol** [comment]
Lol, that is so simple.  I was waaaay overthinking this.  Thanks!

**Comment by adbario** [comment]
No problem, happy coding :)
