### ISSUE TITLE
$format not declared in function

### ISSUE THREAD

**Issue by fastsol** [adbario/slim-secure-session-middleware#9]
Hello,
I was trying to use the clearFrom() and was given an undefined index error for $format.  After looking at the function it seems that $format is not set beforehand.  Then it is also trying to be passed to the clear() as 2nd parameter, but looking at the clear() code there is no 2nd parameter being taken in.

`public function clearFrom($namespace, $key = null)
    {
        if (isset($_SESSION[$namespace]) || $format === true) {
            $oldNamespace = $this->namespace;
            $this->setNamespace($namespace);
            $this->clear($key, $format);
            $this->setNamespace($oldNamespace);
        }
    }`

`public function clear($key = null)
    {
        if (is_string($key)) {
            // Clear the path
            $this->set($key, []);
        } elseif (is_array($key)) {
            // Iterate an array of paths
            foreach ($key as $k) {
                $this->clear($k);
            }
        } elseif (is_null($key)) {
            // Clear all the stored arrays
            $this->array = [];
        }
    }`

**Comment by adbario** [comment]
Hi, thanks for posting. You're absolutely right, there was some leftovers from previous versions. Code is fixed now.
